# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McwDqZneEAttvjy0O-FJNCbDB_viP7gd
"""

import math

# Initialize the board
board = [' ' for _ in range(9)]

def print_board(b):
    print(f"\n {b[0]} | {b[1]} | {b[2]} ")
    print("---|---|---")
    print(f" {b[3]} | {b[4]} | {b[5]} ")
    print("---|---|---")
    print(f" {b[6]} | {b[7]} | {b[8]} \n")

def is_winner(b, letter):
    # Check rows, columns, and diagonals
    winning_conditions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
        (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
        (0, 4, 8), (2, 4, 6)             # Diagonals
    ]
    return any(b[i] == b[j] == b[k] == letter for i, j, k in winning_conditions)

def is_board_full(b):
    return ' ' not in b

def get_empty_cells(b):
    return [i for i, spot in enumerate(b) if spot == ' ']

# Minimax algorithm for unbeatable AI
def minimax(b, is_maximizing):
    if is_winner(b, 'O'):
        return 1
    if is_winner(b, 'X'):
        return -1
    if is_board_full(b):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for cell in get_empty_cells(b):
            b[cell] = 'O'
            score = minimax(b, False)
            b[cell] = ' '
            best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for cell in get_empty_cells(b):
            b[cell] = 'X'
            score = minimax(b, True)
            b[cell] = ' '
            best_score = min(score, best_score)
        return best_score

def ai_move(b):
    best_score = -math.inf
    move = None
    for cell in get_empty_cells(b):
        b[cell] = 'O'
        score = minimax(b, False)
        b[cell] = ' '
        if score > best_score:
            best_score = score
            move = cell
    b[move] = 'O'

def player_move(b):
    while True:
        try:
            choice = int(input("Choose a position (0-8): "))
            if b[choice] == ' ':
                b[choice] = 'X'
                break
            else:
                print("That spot is taken! Try again.")
        except (ValueError, IndexError):
            print("Invalid input. Enter a number between 0 and 8.")

# Main Game Loop
print("Welcome to Tic-Tac-Toe!")
print("You are 'X' and the AI is 'O'.")
print_board(board)

while True:
    player_move(board)
    print_board(board)
    if is_winner(board, 'X'):
        print("You win!")
        break
    if is_board_full(board):
        print("It's a tie!")
        break

    print("AI's turn...")
    ai_move(board)
    print_board(board)
    if is_winner(board, 'O'):
        print("AI wins!")
        break
    if is_board_full(board):
        print("It's a tie!")
        break